FROM node:18.16.0-alpine3.17 As development

ARG NODE_ENV

LABEL maintainer="UniCourt" \
    version="1.0.0" \
    description="Docker image for Workshop 5"

WORKDIR /home/Backend/nest-backend

COPY Backend/nest-backend/package.json ./

RUN npm install -g @nestjs/cli

RUN npm install

COPY Backend/nest-backend/ ./

RUN npm run build

RUN if [[ "$NODE_ENV" != "dev" ]] ; then npm prune --production ; fi